### PR TITLE
Fix bug with default_realm

### PR DESCRIPTION
**Pull request by fjvt**
IF you put the default_realm = none BEFORE The check for token it gets set to None and never gets reset since that only happens on login with username/password.

### CODE REVIEW

**Review by mohierf — CHANGES_REQUESTED** [review]
Please fix the trailing spaces according to https://travis-ci.org/Alignak-monitoring-contrib/alignak-module-ws/builds/233023855?utm_source=github_status&utm_medium=notification

**Comment by mohierf** [comment]
Thanks @fjvt 
Please fix the trailing spaces according to https://travis-ci.org/Alignak-monitoring-contrib/alignak-module-ws/builds/233023855?utm_source=github_status&utm_medium=notification

**Comment by fjvt** [comment]
Fixed the whitespaces ...

**Comment by mohierf** [comment]
Please rebase your commits into one single commit. I try to maintain this repo history as clean as possible ...

**Comment by mohierf** [comment]
@fjvt : I do not merge nor close this... it may wait for you to rebase. I will explain how to with pycharm 😉

**Comment by mohierf** [comment]
I am closing. The fix was introduced in the last released version

**Pull request closed without merging**
