### PR TITLE
Include logcheckresult in the history output

### PR DESCRIPTION
**Pull request by fjvt**
Add the field to the projection list + embed

### CODE REVIEW

**Comment by mohierf** [comment]
Please update the test module accordingly because the tests are broken (*test/test_module_history.py*)

**Comment by mohierf** [comment]
An interesting idea may be to backport the logcheckresult information into the main fetched items. This to avoir duplicate information and limit the siez of the response.
The result of the WS should be:
```
[
    {
        "_created": "Thu, 01 Jun 2017 13:20:04 GMT",
        "_id": "59301484eab423099c1e3c51",
        "acknowledged": false,
        "acknowledgement_type": 1,
        "downtimed": false,
        "execution_time": 0.1165220737,
        "host_name": "srv001",
        "last_check": 1496323202,
        "last_state": "OK",
        "last_state_changed": 0,
        "last_state_id": 0,
        "last_state_type": "HARD",
        "latency": 1.9810860156999999,
        "long_output": "",
        "message": "OK[HARD] (False/False): PROCS OK: 0 processes with STATE = Z",
        "output": "PROCS OK: 0 processes with STATE = Z",
        "passive_check": false,
        "perf_data": "procs=0;5;10;0;",
        "service_name": "linux_nrpe_zombies",
        "state": "OK",
        "state_changed": false,
        "state_id": 0,
        "state_type": "HARD",
        "type": "check.result",
        "user_name": "Alignak"
    },
    {
        "_created": "Thu, 01 Jun 2017 13:19:33 GMT",
        "_id": "59301465eab423099c1e3c4f",
        "acknowledged": false,
        "acknowledgement_type": 1,
        "downtimed": false,
        "execution_time": 0.1138601303,
        "host_name": "srv001",
        "last_check": 1496322894,
        "last_state": "CRITICAL",
        "last_state_changed": 0,
        "last_state_id": 0,
        "last_state_type": "HARD",
        "latency": 2.3519508839,
        "long_output": "",
        "message": "CRITICAL[HARD] (False/False): NRPE: Command 'check_tmp' not defined",
        "output": "NRPE: Command 'check_tmp' not defined",
        "passive_check": false,
        "perf_data": "",
        "service_name": "linux_nrpe_disk_tmp",
        "state": "CRITICAL",
        "state_changed": false,
        "state_id": 2,
        "state_type": "HARD",
        "type": "check.result",
        "user_name": "Alignak"
    },
    ...
    ...
    ...
    {
        "_created": "Wed, 31 May 2017 14:17:47 GMT",
        "host_name": "srv001",
        "message": "Re-check requested from WebUI",
        "service_name": "",
        "type": "check.requested",
        "user_name": "admin"
    },
    {
        "_created": "Wed, 31 May 2017 14:17:45 GMT",
        "host_name": "srv001",
        "message": "Re-check requested from WebUI",
        "service_name": "",
        "type": "check.request",
        "user_name": "admin"
    }
]
```

**Comment by fjvt** [comment]
I would prefer not to do that

if you ever have 2 fields which are similar there is no way of knowing where they came from

for example _created 

which created is it then ? That of the history object or the logcheckresult ? (_created may be a bad example as _Created of both will be identical)

Alternatively you can add a prefix ('logcheckresult_') but again it makes it more complex. The data model says logcheckresult is a reference to another collection , as such the data of that collection should be included (similar to what the backend does if you chose 'embedded' which is the method i used in WS to get the logcheckresult)

**Comment by mohierf** [comment]
Ok with your last comment. But:
 - some inner backend firlds are still removed: `_etag`, `_links`, ...
 - `host_name` and `service_name` will be duplicated
 - `host`, `service`, `_realm`, `_sub_realm`  will be of no interest on this interface

I propose to keep the `logcheckresult` but clean the unuseful here mentionned fields?

**Comment by mohierf** [comment]
Included in #51

**Pull request closed without merging**
